services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=x0lFM0AHFumZR07_a0ft
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - es_data:/usr/share/elasticsearch/data


  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    ports:
      - "5044:5044"
      - "9600:9600"
      - "12201:12201/udp" # GELF UDP port
      - "12201:12201"     # GELF TCP port (if needed)
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml 


  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml


volumes:
  es_data:
    driver: local


networks:
  default:
    external: true
    name: elk_network
